provider:
  name: rfc2136
rfc2136:
  host: coredns-local.local-dns.svc.cluster.local
  port: 53
  zone: example.com.
sources:
  - service
  - gateway-httproute
policy: sync
registry: txt
txtOwnerId: kind-platform-demo
logLevel: info
interval: 30s
replicaCount: 1