provider:
  name: fake

sources:
  - service
  - ingress
  - gateway-httproute

policy: sync
registry: txt
txtOwnerId: kind-platform-demo

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

logLevel: info