apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/nathalawi/platform-gitops
    targetRevision: main
    path: apps/local-dns
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: local-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true