apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-pool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/nathalawi/platform-gitops
    targetRevision: main
    path: infrastructure/metallb/ip-pool.yaml
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
