apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certificates
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:

          - app: argocd
            namespace: argocd
            hostname: argocd.example.com
            tlsSecretName: argocd-tls
            issuerKind: ClusterIssuer
            issuerName: example-local-ca

          - app: backstage
            namespace: backstage
            hostname: backstage.example.com
            tlsSecretName: backstage-tls
            issuerKind: ClusterIssuer
            issuerName: example-local-ca

          - app: prometheus
            namespace: observability
            hostname: prometheus.example.com
            tlsSecretName: prometheus-tls
            issuerKind: ClusterIssuer
            issuerName: example-local-ca

          - app: grafana
            namespace: observability
            hostname: grafana.example.com
            tlsSecretName: grafana-tls
            issuerKind: ClusterIssuer
            issuerName: example-local-ca

          - app: alertmanager
            namespace: observability
            hostname: alertmanager.example.com
            tlsSecretName: alertmanager-tls
            issuerKind: ClusterIssuer
            issuerName: example-local-ca

  template:
    metadata:
      name: cert-{{.app}}
      annotations:
        argocd.argoproj.io/sync-wave: "20"
    spec:
      project: infrastructure
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      source:
        repoURL: https://github.com/nathalawi/platform-gitops
        targetRevision: main
        path: charts/certificates-app
        helm:
          values: |
            app: {{.app}}
            namespace: {{.namespace}}
            hostname: {{.hostname}}
            tlsSecretName: {{.tlsSecretName}}
            issuer:
              kind: {{.issuerKind}}
              name: {{.issuerName}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true